# Generated by Django 5.2.3 on 2025-06-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_post', '0002_remove_post_content_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article_post.post')),
                ('event_date_time', models.DateTimeField(help_text='Укажите дату и время, когда событие будет происходить', verbose_name='Дата и время события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
            bases=('article_post.post',),
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='defaults/default_cover.jpg', null=True, upload_to='post_covers/', verbose_name='Обложка поста'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='wost_covers/wallpaperbetter.jpg', upload_to='post_images/', verbose_name='Изображение в тексте'),
        ),
    ]
