# Generated by Django 5.2.3 on 2025-07-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_post', '0003_alter_comment_ip_address_alter_comment_user_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
