# Generated by Django 5.2.3 on 2025-06-28 21:48

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeMemberForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Фамилия Имя Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения (число, месяц, год)')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ', verbose_name='Номер телефона')),
                ('telegram_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram аккаунт')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='E-Mail')),
                ('address', models.TextField(verbose_name='Домашний адрес')),
                ('greek_ancestor_relation', models.CharField(default=None, max_length=100, verbose_name='Кто из ваших предков является греком?')),
                ('greek_ancestor_surname', models.CharField(max_length=100, verbose_name='Фамилия вашего греческого предка')),
                ('about_yourself', models.TextField(blank=True, null=True, verbose_name='Дополнительные сведения о себе')),
                ('interested_activities', models.TextField(help_text='Например, кулинарные мастер-классы, изучение греческого языка и т.п.', verbose_name='Интересующая общественная деятельность')),
                ('your_contribution', models.TextField(help_text='Например, проведение мастер-классов, тренингов и т.п.', verbose_name='Ваш вклад в развитие и функционирование центра')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка в Греческий Культурный Центр',
                'verbose_name_plural': 'Заявки в Греческий Культурный Центр',
            },
        ),
    ]
