# Generated by Django 5.2.3 on 2025-07-14 06:27

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bememberform',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='bememberform',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ', unique=True, verbose_name='Номер телефона'),
        ),
    ]
