# Generated by Django 5.2.3 on 2025-06-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bememberform',
            name='status',
            field=models.CharField(choices=[('pending', 'Не отвечает'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='Статус заявки'),
        ),
    ]
