# Generated by Django 5.2.3 on 2025-06-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bememberform',
            name='greek_ancestor_relation',
            field=models.CharField(default=None, help_text='Если таких нет - напишите Нет', max_length=100, verbose_name='Кто из ваших предков является греком?'),
        ),
        migrations.AlterField(
            model_name='bememberform',
            name='greek_ancestor_surname',
            field=models.CharField(help_text='Если таких нет - напишите Нет', max_length=100, verbose_name='Фамилия вашего греческого предка'),
        ),
    ]
