# Generated by Django 5.2.3 on 2025-06-28 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('description', models.TextField(verbose_name='Полный текст')),
                ('cover', models.ImageField(blank=True, default='defaults/default_cover.jpg', null=True, upload_to='post_covers/', verbose_name='Обложка поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article_post.post')),
                ('event_date_time', models.DateTimeField(help_text='Укажите дату и время, когда событие будет происходить', verbose_name='Дата и время события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
            bases=('article_post.post',),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='wost_covers/wallpaperbetter.jpg', upload_to='post_images/', verbose_name='Изображение в тексте')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись к изображению')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='article_post.post', verbose_name='Пост')),
            ],
        ),
    ]
